#ifndef __INFO_HELPER_H__
#define __INFO_HELPER_H__


#include <iostream>
#include <fstream>
#include <streambuf>
#include <vector>
#include <string>
#include <memory.h>
#include <cstring>
#include <syncstream>
#include <iomanip>
#include <random>
#include <atomic>
//#include "attribute.h"
//#include "dataset.h"
#include "optimizers.h"
#include "matrix.h"
//#include "../util/csv_file.h"

namespace provallo
{


    //optimal spike decoding filter :
    //optimal linear kernel for spike train decoding 
    //see : https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2781884/
    //fisher information : 
    //https://en.wikipedia.org/wiki/Fisher_information
    //https://en.wikipedia.org/wiki/Linear_discriminant_analysis
    //https://en.wikipedia.org/wiki/Kernel_Fisher_discriminant_analysis

//joint distribution of spike train and stimulus
//p(s,x) = p(s|x) * p(x):
//p(s|x) = p(s,x) / p(x)
//p(x) = sum_s p(s,x)
//p(s|x) = p(s,x) / sum_s p(s,x)

    real_t joint_distribution(const std::vector<real_t> &spike_train, const std::vector<real_t> &stimulus)
    {
        real_t sum = 0.0;
        for (size_t i = 0; i < spike_train.size(); i++)
        {
            sum += spike_train[i] * stimulus[i];
        }
        return sum;
    }   
    real_t marginal_distribution(const std::vector<real_t> &spike_train)
    {
        real_t sum = 0.0;
        for (size_t i = 0; i < spike_train.size(); i++)
        {
            sum += spike_train[i];
        }
        return sum;
    }       
    real_t conditional_distribution(const std::vector<real_t> &spike_train, const std::vector<real_t> &stimulus)
    {
        return joint_distribution(spike_train, stimulus) / marginal_distribution(spike_train);
    }


    



    real_t fisher_information(const std::vector<real_t> &spike_train, real_t sigma= 1.0)
    {
        real_t sum = 0.0;
        for (size_t i = 0; i < spike_train.size(); i++)
        {
            sum += spike_train[i] * spike_train[i];
        }
        return sum / (sigma * sigma);
    }
    real_t linear_discriminant_analysis(const std::vector<real_t> &spike_train, real_t sigma = 1.0)
    {
        return fisher_information(spike_train, sigma);
    }       
    real_t kernel_fisher_discriminant_analysis(const std::vector<real_t> &spike_train, real_t sigma = 1.0)
    {
        return fisher_information(spike_train, sigma);
    }

    //recognition model :
    //https://en.wikipedia.org/wiki/Recognition_model
    //https://en.wikipedia.org/wiki/Recognition_model#Recognition_model_for_continuous_variables
    //https://en.wikipedia.org/wiki/Recognition_model#Recognition_model_for_discrete_variables


    
    //FACTORIAL CODING ,sparse coding dimensionality reduction:
    //https://en.wikipedia.org/wiki/Sparse_coding

    //https://en.wikipedia.org/wiki/Independent_component_analysis
    //https://en.wikipedia.org/wiki/Non-negative_matrix_factorization
    //https://en.wikipedia.org/wiki/Non-negative_matrix_factorization#Sparse_coding
    //https://en.wikipedia.org/wiki/Non-negative_matrix_factorization#Non-negative_sparse_coding

    //use gaussian mixture models for clustering : 
    //https://en.wikipedia.org/wiki/Mixture_model#Gaussian_mixture_model

    //https://en.wikipedia.org/wiki/Expectation%E2%80%93maximization_algorithm
    //https://en.wikipedia.org/wiki/Expectation%E2%80%93maximization_algorithm#Gaussian_mixture
    //https://en.wikipedia.org/wiki/Expectation%E2%80%93maximization_algorithm#Gaussian_mixture

    //Generative models: 
    //mixing proportions :
    //https://en.wikipedia.org/wiki/Mixture_model#Gaussian_mixture_model
    //https://en.wikipedia.org/wiki/Mixture_model#Gaussian_mixture_model



    //marginal distribution
    //p[u;G] = sum_k p[u,k;G] = sum_k p[u|k;G] * p[k;G]
    //p[u|k;G] = p[u,k;G] / p[k;G]
    //p[k;G] = sum_u p[u,k;G]
    //p[u|k;G] = p[u,k;G] / sum_u p[u,k;G]

    //joint distribution p[v,u;G] = p[v|u;G] * p[u;G]
    //p[v|u;G] = p[v,u;G] / p[u;G]
    //p[v,u;G] = p[v|u;G] * p[u;G]


    //recognition distribution (statistical inverse of the generative model):
    //the generative model can be used to generate samples from the distribution 
    //it is defined as P[v|u;G] = P[u|v;G] * P[v;G] / P[u;G]
    //and indicates how likely it is that a given sample v was generated by the generative model 
    //for instance P[v=A|u;G]=0.8 indicates that the sample v= neuron A was generated by the generative model with a probability of 0.8 
    //and P[v=B|u;G]=0.2 indicates that the sample v= neuron B was generated by the generative model with a probability of 0.2 

    
    template <typename T> 
    class gaussian_spike_train_generator
    {  
        private: 
        real_t _sigma; //standard deviation of the gaussian distribution
        real_t _mu; //mean of the gaussian distribution
        real_t _dt; //time step
        real_t _t; //current time
        real_t _t_max; //maximum time
        real_t _t_min; //minimum time
        real_t _t_step; //time step
        //mixing proportions :
        real_t _p; //probability of a spike
        real_t _q; //probability of no spike
        //generative model :
        //G = {p[u|k;G], p[k;G]} 
        std::vector<real_t> _G; //generative model
        
        //p[u;G] = sum_k p[u,k;G] = sum_k p[u|k;G] * p[k;G]
        //p[u|k;G] = p[u,k;G] / p[k;G]
        //random distribution :
        std::vector<real_t> _p_u_k_G; //p[u,k;G]
        std::vector<real_t> _p_u_G; //p[u;G]
        std::vector<real_t> _p_k_G; //p[k;G]
        //joint distribution :
        //p[v,u;G] = p[v|u;G] * p[u;G]
        //p[v|u;G] = p[v,u;G] / p[u;G]
        std::vector<real_t> _joint_distribution; //p[v,u;G]
        
        //recognition distribution :
        //P[v|u;G] = P[u|v;G] * P[v;G] / P[u;G]
        std::vector<real_t> _recognition_distribution; //P[v|u;G]

        //recognition model :
        //P[u|v;G] = P[v|u;G] * P[u;G] / P[v;G]
        std::vector<real_t> _recognition_model; //P[u|v;G]

        //random uniform distribution :
        std::vector<real_t> _p_u_k; //p[u,k]
        std::vector<real_t> _p_u; //p[u]
        std::vector<real_t> _p_k; //p[k]

        std::vector<real_t> _output; //output of the generator

        std::vector<real_t> _input; //aggregate input of the generator


        public:
        gaussian_spike_train_generator(real_t sigma, real_t mu, real_t dt, real_t t_min, real_t t_max   )
        : _sigma(sigma) , _mu(mu) , _dt(dt) ,_t(t_min) , _t_max(t_max),_t_min(t_min), _t_step(t_min), _p(0.5), _q(0.5), _G(2), _p_u_k_G(2), _p_u_G(2), _p_k_G(2), _joint_distribution(2), _recognition_distribution(2), _recognition_model(2), _p_u_k(2), _p_u(2), _p_k(2)
        {
            init();
        }
        ~gaussian_spike_train_generator()
        {
        }
        void reset()
        {
            _t_step = _t_min;
            _t = _t_min;
        }
        void set_sigma(real_t sigma)
        {
            _sigma = sigma;
        }
        void set_mu(real_t mu)
        {
            _mu = mu;
        }
        void set_dt(real_t dt)
        {
            _dt = dt;
        }
        void set_t_min(real_t t_min)
        {
            _t_min = t_min;
        }
        void set_t_max(real_t t_max)
        {
            _t_max = t_max;
        }
        void set_t_step(real_t t_step)
        {
            _t_step = t_step;
        }
        real_t get_sigma() const
        {
            return _sigma;
        }
        real_t get_mu() const
        {
            return _mu;
        }
        real_t get_dt() const
        {
            return _dt;
        }
        real_t get_t_min() const
        {
            return _t_min;
        }
        real_t get_t_max() const
        {
            return _t_max;
        }
        real_t get_t_step() const
        {
            return _t_step;
        }
        real_t get_t() const
        {
            return _t;
        }
        void set_p(real_t p)
        {
            _p = p;
        }
        void set_q(real_t q)
        {
            _q = q;
        }
        real_t get_p() const
        {
            return _p;
        }
        real_t get_q() const
        {
            return _q;
        }
        void set_generative_model(const std::vector<real_t> &G)
        {
            _G = G;
        }   
        const std::vector<real_t> & get_generative_model() const
        {
            return _G;
        }
        void set_random_distribution(const std::vector<real_t> &p_u_k_G)
        {
            _p_u_k_G = p_u_k_G;
        }
        const std::vector<real_t> & get_random_distribution() const
        {
            return _p_u_k_G;
        }
        void set_joint_distribution(const std::vector<real_t> &joint_distribution)
        {
            _joint_distribution = joint_distribution;
        }
        const std::vector<real_t> & get_joint_distribution() const
        {
            return _joint_distribution;
        }
        void set_recognition_distribution(const std::vector<real_t> &recognition_distribution)
        {
            _recognition_distribution = recognition_distribution;
        }
        const std::vector<real_t> & get_recognition_distribution() const
        {
            return _recognition_distribution;
        }

        void set_recognition_model(const std::vector<real_t> &recognition_model)
        {
            _recognition_model = recognition_model;
        }
        const std::vector<real_t> & get_recognition_model() const
        {
            return _recognition_model;
        }

        void set_random_uniform_distribution(const std::vector<real_t> &p_u_k)
        {
            _p_u_k = p_u_k;
        }
        const std::vector<real_t> & get_random_uniform_distribution() const
        {
            return _p_u_k;
        }
        void set_p_u(const std::vector<real_t> &p_u)
        {
            _p_u = p_u;
        }
        const std::vector<real_t> & get_p_u() const
        {
            return _p_u;
        }
        void set_p_k(const std::vector<real_t> &p_k)
        {
            _p_k = p_k;
        }
        const std::vector<real_t> & get_p_k() const
        {
            return _p_k;
        }



        //initialize the generator :
        void init()
        {
            std::uniform_real_distribution<real_t> distribution(0.0, 1.0);
            std::uniform_int_distribution<int> distribution_int(0, 1);
            std::random_device rd;
            std::mt19937 gen(rd());
            //initialize the random distribution :
            //p[u,k;G] = p[u|k;G] * p[k;G]

            size_t n = (_t_max - _t_min) / _dt;
            _p_u_k_G.resize(n);
            _p_u_G.resize(n);
            _p_k_G.resize(n);
            _joint_distribution.resize(n);
            _recognition_distribution.resize(n);
            _recognition_model.resize(n);
            _p_u_k.resize(n);
            _p_u.resize(n);
            _p_k.resize(n);
            reset();
            //set random values for the generative model :
            for (size_t i = 0; i < n; i++)
            {
                _p_u_k_G[i] = distribution(gen);
                _p_u_G[i] = distribution(gen);
                _p_k_G[i] = distribution(gen);
                
                _p_u_k[i] = distribution(gen);
                _p_u[i] = distribution(gen);
                _p_k[i] = distribution(gen);
                _joint_distribution[i] = distribution(gen);
                _recognition_distribution[i] = distribution(gen);
                _recognition_model[i] = distribution(gen);

            }   
            //set gaussian /mixed  distribution :
            //p[u,k;G] = p[u|k;G] * p[k;G]
            //p[u|k;G] = p[u,k;G] / p[k;G]
            //p[k;G] = sum_u p[u,k;G]
            //p[u|k;G] = p[u,k;G] / sum_u p[u,k;G]





            for (size_t i = 0; i < n; i++)
            {
                _p_k[i]= _p_u_k_G[i]/_p_u_k[i];
                _p_u[i]= _p_u_k_G[i]/_p_k[i];
                _p_u_k[i] = _p_u_k_G[i] / _p_k[i];
                _p_u_G[i]= _p_u_k_G[i]/_p_k_G[i];
                _p_u_k_G[i] = _p_u_k[i] * _p_k[i];
                _p_u_G[i]= _p_u_k_G[i]/_p_k_G[i];
                _p_k_G[i]= _p_u_k_G[i]/_p_u_G[i];
                _joint_distribution[i] = _p_u_k_G[i] * _p_u_G[i];
                _recognition_distribution[i] = _p_u_k_G[i] * _p_u_G[i];
                _recognition_model[i] = _p_u_k_G[i] * _p_u_G[i];

            }   

        }
        
        //refine the generator with EM algorithm :
        //gamma : mixing proportions 
        //https://en.wikipedia.org/wiki/Mixture_model#Gaussian_mixture_model
        real_t refine(const std::vector<real_t> input)
        {
            real_t result=0.0;
            this->_p = 0.5;
            this->_q = 1.0 - this->_p;
            this->_input.resize(_input.size()+input.size());
            this->_input.insert(this->_input.end(), input.begin(), input.end());
            std::uniform_real_distribution<real_t> distribution(0.0, 1.0);
            std::uniform_int_distribution<int> distribution_int(0, 1);
            provallo::Gaussian<real_t> gaussian(0.0, 1.0);
            std::vector<real_t> results(input.size());
            matrix<real_t> gamma(input.size(), _G.size());
            matrix<real_t> SIGMA(input.size(), _G.size());
            matrix<real_t> gv(input.size(), _G.size());
            std::vector<real_t> generative(input.size());
            std::vector<real_t> recognition(input.size());
              //separate invertible and non-invertible matrices :
            matrix<real_t> invertible_gamma(input.size(), _G.size());
            matrix<real_t> invertible_SIGMA(input.size(), _G.size());
            matrix<real_t> invertible_gv(input.size(), _G.size());
            matrix<real_t> non_invertible_gamma(input.size(), _G.size());
            matrix<real_t> non_invertible_SIGMA(input.size(), _G.size());
            matrix<real_t> non_invertible_gv(input.size(), _G.size());
            matrix<real_t> gaussian_matrix(input.size(), _G.size());
            //initialize gamma <P([v|u;G])> :
            for (size_t i = 0; i < input.size(); i++)
            {
                for (size_t j = 0; j < _G.size(); j++)
                {
                    real_t gauss = gaussian();

                    gamma(i,j) = _G[j] * input[i]   ;
                    SIGMA(i,j)  = input[i]/2.0*gamma(i,j);
                    gv(i,j) = gamma(i,j) * _p_u_k_G[i];
                    gaussian_matrix(i,j) =gauss;


                    //separate invertible and non-invertible matrices :
                    invertible_gamma(i,j) = gamma(i,j);
                    invertible_SIGMA(i,j)  = SIGMA(i,j);
                    invertible_gv(i,j) = gv(i,j);
                    non_invertible_gamma(i,j) = gamma(i,j);
                    non_invertible_SIGMA(i,j)  = SIGMA(i,j);
                    non_invertible_gv(i,j) = gv(i,j);
                    _p  +=   _p_u_k_G[i] * _p_u_G[i];
                    _q  +=   _p_u_k_G[i] * _p_u_G[i];
                    gaussian.set_mean(_G[j]);
                    gaussian.set_variance(SIGMA(i,j));
                                     
                }
                generative[i] = _G[i] * input[i] * _p_u_k_G[i] * _p_u_G[i];

                recognition[i] = _G[i] * input[i] * _p_u_k_G[i] * _p_u_G[i];
                result += generative[i];
            }
            _p= _p/input.size();
            _q= _q/input.size();
            //initialize joint distribution :
            this->_joint_distribution.resize(input.size());
            for (size_t i = 0; i < input.size(); i++)
            {
                this->_joint_distribution[i] = recognition[i] * generative[i];
            }
            //initialize recognition distribution :
            this->_recognition_distribution.resize(input.size());
            for (size_t i = 0; i < input.size(); i++)
            {
                this->_recognition_distribution[i] = recognition[i] * generative[i];
            }   
            //initialize recognition model :
            this->_recognition_model.resize(input.size());
            for (size_t i = 0; i < input.size(); i++)
            {
                this->_recognition_model[i] = recognition[i] * generative[i];
            }
            
            //use the gaussian matrix to compute the inverse of the matrices : 
            invertible_gamma= invertible_gamma * gaussian_matrix;
            invertible_SIGMA= invertible_SIGMA * gaussian_matrix;
            invertible_gv= invertible_gv * gaussian_matrix;


            invertible_gamma.invert();
            invertible_SIGMA.invert();
            invertible_gv.invert();


            
            //prepare the EM algorithm :

            //E-step :
            //compute the expectation of the log-likelihood :
            //Q[v;u]    =  P[v|u;G] * P[u;G] * log(P[v|u;G] * P[u;G]) + P[v|u;G] * P[u;G] * log(P[v|u;G] * P[u;G]) 

            //M-step :
            
            //maximize the expectation of the log-likelihood :
            //use DKL to maximize the expectation of the log-likelihood :
            //DKL = sum_v P[v|u;G] * P[u;G] * log(P[v|u;G] * P[u;G] / P[v;G])
            //    = sum_v P[v|u;G] * P[u;G] * log(P[v|u;G] * P[u;G]) - sum_v P[v|u;G] * P[u;G] * log(P[v;G])
            //l(G)  =   <ln P[v|u;G]> - <ln P[v;G]>
            //      =   <ln P[v|u;G]> - <ln P[v;G]>


            //compute the expectation of the log-likelihood :
            //and maximize it :

            //Q[v;u]    =  P[v|u;G] * P[u;G] * log(P[v|u;G] * P[u;G]) + P[v|u;G] * P[u;G] * log(P[v|u;G] * P[u;G])
            //DKL = sum_v P[v|u;G] * P[u;G] * log(P[v|u;G] * P[u;G] / P[v;G])
            
            std::vector<real_t> Q(input.size(),0.0),DKL(input.size(),0.0),F(input.size(),0.0),W(input.size(),0.0); 
          
            matrix<real_t> g(input.size(), _G.size());
            for (size_t i = 0; i <g.size1();i++)
            {
                //g(i,j) = _G[j] * input[i] * _p_u_k_G[i] * _p_u_G[i];
                for ( size_t j = 0; j < g.size2(); j++  )
                {
                    g(i,j) = _G[j] * input[i] * _p_u_k_G[i] * _p_u_G[i];
                }   

                g(i,i) = _G[i] * input[i] * _p_u_k_G[i] * _p_u_G[i];
                
            }
            


            for (size_t i = 0; i < input.size(); i++)
            {
                Q[i] = recognition[i] * generative[i] * std::log(recognition[i] * generative[i]) + recognition[i] * generative[i] * std::log(recognition[i] * generative[i]);
                DKL[i] = Q[i] - ( recognition[i] * generative[i] * std::log(recognition[i] * generative[i] / recognition[i]) ); 
                W[i] = (Q[i] - DKL[i] ) / Q[i];
                F[i] = Q[i] - DKL[i] + W[i] * DKL[i] ;
            }
            //sum everything 
            result = 0.0;
            for (size_t i = 0; i < input.size(); i++)
            {
                result += F[i];
            }       
            //maximize the expectation of the log-likelihood :
            //use DKL to maximize the expectation of the log-likelihood :
            //DKL = sum_v P[v|u;G] * P[u;G] * log(P[v|u;G] * P[u;G] / P[v;G])

            //F(Q,G) = sum_v Q[v;u] ln  P[v|u;G] * P[u;G] - sum_v Q[v;u]    ln P[v|u;G] * P[u;G] / Q[v;u]   =
            //-1/2sigma|u - G * v|^2 + ln P[u;G] - ln P[u;G] / Q[v;u]


            
            //F(Q,G) = sum_v Q[v;u] ln  P[v|u;G] * P[u;G] - sum_v Q[v;u] ln P[v,u;G] / Q[v;u]   
            //F(Q,G) = sum_v Q[v;u] ln  P[v|u;G] * P[u;G] - sum_v Q[v;u] ln P[v|u;G] * P[u;G] / Q[v;u]


            //=L(G)-DKL(Q[v;u],P[v|u;G] * P[u;G])   
            //L(G) = sum_v Q[v;u] ln  P[v|u;G] * P[u;G] - sum_v Q[v;u] ln P[v|u;G] * P[u;G] / Q[v;u] + DKL(Q[v;u],P[v|u;G] * P[u;G])
            //maximize and set _output to the results  :



            for ( size_t i=0 ; i < input.size(); i++ )
            {
                _output[i] = F[i];
            }
            //return the sum of the output :

            return result;


        }

        //generate a spike train :
        std::vector<real_t> generate()
        {
            std::vector<real_t> result;
            std::uniform_real_distribution<real_t> distribution(0.0, 1.0);
            std::uniform_int_distribution<int> distribution_int(0, 1);
            std::random_device rd;
            std::mt19937 gen(rd());
            //generate a spike train :
            while (_t_step < _t_max)
            {
                _t_step += _dt;
                _t += _dt;
                if (distribution(gen) < _p)
                {
                    result.push_back(1.0);
                }
                else
                {
                    result.push_back(0.0);
                }
            }
            return result;
        }       
        //generate a spike train :
        std::vector<real_t> operator()()
        {
            return generate();
        }   

        //generate a spike train :
        std::vector<real_t> operator()(real_t sigma, real_t mu, real_t dt, real_t t_min, real_t t_max)
        {
            set_sigma(sigma);
            set_mu(mu);
            set_dt(dt);
            set_t_min(t_min);
            set_t_max(t_max);
            return generate();
        }
        //generate a spike train with input :
        std::vector<real_t> operator()(const std::vector<real_t> &input)
        {
            return refine(input);
        }   
        //generate a spike train with input :
        std::vector<real_t> operator()(const std::vector<real_t> &input, real_t sigma, real_t mu, real_t dt, real_t t_min, real_t t_max)
        {
            set_sigma(sigma);
            set_mu(mu);
            set_dt(dt);
            set_t_min(t_min);
            set_t_max(t_max);
            return refine(input);
        }
        //generate a spike train with input :
        std::vector<real_t> operator()(const std::vector<real_t> &input, real_t sigma, real_t mu, real_t dt, real_t t_min, real_t t_max, const std::vector<real_t> &G)
        {
            set_sigma(sigma);
            set_mu(mu);
            set_dt(dt);
            set_t_min(t_min);
            set_t_max(t_max);
            set_generative_model(G);
            return refine(input);
        }
        //gnuplot output :
        void gnuplot(const std::string& file)
        {
            //create .dat file for multiple plots : 
            std::ofstream out(file + ".dat");
            out << "#t input  " << "\t" << "output" << std::endl;
            for (size_t i = 0; i < _output.size(); i++)
            {
                out << i << "\t" <<  _input[i] <<"\t"<< _output[i] << std::endl;

            }


            out.close();


        }

        //sum of output :
        real_t sum ( )const 
        {
            real_t result=0.0;
            for(size_t i=0;i<_output.size();i++)
            {
                result += _output[i];
            }
            return result;
        }

        //mean of output :
        real_t mean ( )const 
        {
            real_t result=0.0;
            for(size_t i=0;i<_output.size();i++)
            {
                result += _output[i];
            }
            return result/_output.size();
        }   
        //variance of output :
        real_t variance ( )const 
        {
            real_t result=0.0;
            real_t mean = this->mean();
            for(size_t i=0;i<_output.size();i++)
            {
                result += (_output[i]-mean)*(_output[i]-mean);
            }
            return result/_output.size();
        }
        //standard deviation of output :
        real_t standard_deviation ( )const 
        {
            return sqrt(variance());
        }
        //skewness of output :
        real_t skewness ( )const 
        {
            real_t result=0.0;
            real_t mean = this->mean();
            real_t standard_deviation = this->standard_deviation();
            for(size_t i=0;i<_output.size();i++)
            {
                result += (_output[i]-mean)*(_output[i]-mean)*(_output[i]-mean);
            }
            return result/(_output.size()*standard_deviation*standard_deviation*standard_deviation);
        }   
        //kurtosis of output :
        real_t kurtosis ( )const 
        {
            real_t result=0.0;
            real_t mean = this->mean();
            real_t standard_deviation = this->standard_deviation();
            for(size_t i=0;i<_output.size();i++)
            {
                result += (_output[i]-mean)*(_output[i]-mean)*(_output[i]-mean)*(_output[i]-mean);
            }
            return result/(_output.size()*standard_deviation*standard_deviation*standard_deviation*standard_deviation);
        }       
        //entropy of output :
        real_t entropy ( )const 
        {
            real_t result=0.0;
            for(size_t i=0;i<_output.size();i++)
            {
                result += _output[i]*std::log(_output[i]);
            }
            return result;
        }
        //cross entropy of output :
        real_t cross_entropy ( )const 
        {
            real_t result=0.0;
            for(size_t i=0;i<_output.size();i++)
            {
                result += _output[i]*std::log(_output[i]);
            }
            return result;
        }   
        //KL divergence of output :
        real_t KL_divergence ( )const 
        {
            real_t result=0.0;
            for(size_t i=0;i<_output.size();i++)
            {
                result += _output[i]*std::log(_output[i]/_output[i]);
            }
            return result;
        }                           


    };
    //implementation of helmholtz machine :
    //https://en.wikipedia.org/wiki/Helmholtz_machine
    //https://en.wikipedia.org/wiki/Expectation%E2%80%93maximization_algorithm
    //https://en.wikipedia.org/wiki/Generative_model
    //https://en.wikipedia.org/wiki/Recognition_model
    //https://en.wikipedia.org/wiki/Statistical_classification

    template <typename T>
    class helmholtz_machine
    {   
        private: 

        size_t _n;//number of layers
        size_t _m;//number of neurons
        size_t _k;//number of spikes
        size_t _l;//number of spikes
        size_t _t;//time
        size_t _t_step;//time step
        
        gaussian_spike_train_generator<T> _generator;
        std::vector<real_t> _input;
        std::vector<real_t> _output;
        std::vector<real_t> _generative_model;
        std::vector<real_t> _recognition_model;
        std::vector<real_t> _recognition_distribution;
        std::vector<real_t> _random_distribution;
        std::vector<real_t> _joint_distribution;
        std::vector<real_t> _random_uniform_distribution;
        std::vector<real_t> _F_phase;
        std::vector<real_t> _W_phase;
        std::vector<real_t> _Q_phase;
        std::vector<real_t> _DKL_phase;
        

        public:
        helmholtz_machine(size_t n=1, size_t m=1, size_t k=1, size_t l=1, size_t t=0, size_t t_step=0):_generator(n,m,k,l,t,t_step)
        {
        }    
        ~helmholtz_machine()
        {
        }   
        void reset()
        {
            _generator.reset();
        }
        void set_sigma(real_t sigma)
        {
            _generator.set_sigma(sigma);
        }
        void set_mu(real_t mu)
        {
            _generator.set_mu(mu);
        }
        void set_dt(real_t dt)
        {
            _generator.set_dt(dt);
        }
        void set_t_min(real_t t_min)
        {
            _generator.set_t_min(t_min);
        }
        void set_t_max(real_t t_max)
        {
            _generator.set_t_max(t_max);
        }
        void set_t_step(real_t t_step)
        {
            _generator.set_t_step(t_step);
        }
        real_t get_sigma() const
        {
            return _generator.get_sigma();
        }
        real_t get_mu() const
        {
            return _generator.get_mu();
        }
        real_t get_dt() const
        {
            return _generator.get_dt();
        }
        real_t get_t_min() const
        {
            return _generator.get_t_min();
        }
        real_t get_t_max() const
        {
            return _generator.get_t_max();
        }
        real_t get_t_step() const
        {
            return _generator.get_t_step();
        }
        real_t get_t() const
        {
            return _generator.get_t();
        }
        void set_p(real_t p)
        {
            _generator.set_p(p);
        }
        void set_q(real_t q)
        {
            _generator.set_q(q);
        }
        real_t get_p() const
        {
            return _generator.get_p();
        }
        real_t get_q() const
        {
            return _generator.get_q();
        }
        void set_generative_model(const std::vector<real_t> &G)
        {
            _generator.set_generative_model(G);
        }   
        const std::vector<real_t> & get_generative_model() const
        {
            return _generator.get_generative_model();
        }
        void set_random_distribution(const std::vector<real_t> &p_u_k_G)
        {
            _generator.set_random_distribution(p_u_k_G);
        }
        const std::vector<real_t> & get_random_distribution() const
        {
            return _generator.get_random_distribution();
        }
        void set_joint_distribution(const std::vector<real_t> &joint_distribution)
        {
            _generator.set_joint_distribution(joint_distribution);
        }
        const std::vector<real_t> & get_joint_distribution() const
        {
            return _generator.get_joint_distribution();
        }
        void set_recognition_distribution(const std::vector<real_t> &recognition_distribution)
        {
            _generator.set_recognition_distribution(recognition_distribution);
        }
        const std::vector<real_t> & get_recognition_distribution() const
        {
            return _generator.get_recognition_distribution();
        }

        void set_recognition_model(const std::vector<real_t> &recognition_model)
        {
            _generator.set_recognition_model(recognition_model);
        }
        void init()
        {
            _generator.init();
            //initialize the random distribution :
            //p[u,k;G] = p[u|k;G] * p[k;G]
            Gaussian<real_t> gaussian(0.0, 1.0);
            size_t n = (_generator.get_t_max() - _generator.get_t_min()) / _generator.get_dt();
            _random_distribution.resize(n);
            _generative_model.resize(n);
            _recognition_model.resize(n);
            _joint_distribution.resize(n);
            _recognition_distribution.resize(n);
            _random_uniform_distribution.resize(n);
            //set random values for the generative model :
            for (size_t i = 0; i < n; i++)
            {
                            //set gaussian /mixed  distribution :
                            //p[u,k;G] = p[u|k;G] * p[k;G]
                            //p[u|k;G] = p[u,k;G] / p[k;G]
                            //p[k;G] = sum_u p[u,k;G]
                            //p[u|k;G] = p[u,k;G] / sum_u p[u,k;G]


                _random_distribution[i] =gaussian();
                _generative_model[i] = gaussian();
                _recognition_model[i] = gaussian();
                _joint_distribution[i] = gaussian();
                _recognition_distribution[i] = gaussian();
                _random_uniform_distribution[i] = gaussian();
                gaussian.set_mean(_generator.get_generative_model()[i]);
                gaussian.set_variance(_generator.get_sigma());

            }   
            //set gaussian /mixed  distribution :
            //p[u,k;G] = p[u|k;G] * p[k;G]
            //p[u|k;G] = p[u,k;G] / p[k;G]
            //p[k;G] = sum_u p[u,k;G]

            for (size_t i = 0; i < n; i++)
            {
                _generative_model[i] = _generative_model[i] * _random_distribution[i];
                _recognition_model[i] = _recognition_model[i] * _random_distribution[i];
                _joint_distribution[i] = _joint_distribution[i] * _random_distribution[i];
                _recognition_distribution[i] = _recognition_distribution[i] * _random_distribution[i];
                _random_uniform_distribution[i] = _random_uniform_distribution[i] * _random_distribution[i];
            }


            
        }

    };



}



#endif // __INFO_HELPER_H__ 